accounts/urls.py
# from django.urls import path
# from . import views

# app_name = "main"
# urlpatterns = [
#     path('',views.home, name="home"),
#     path('details/<int:id>/',views.detail, name="detail"),
# ]


# from django.urls import path
# from . import views

# app_name = "accounts"
# urlpatterns = [
#     path('register/', views.register, name="register"),
#     path('login/', views.login_view, name='login'),
#     path("logout/", views.logout_user, name="logout")
# ]

from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name="register"),
    path("login/", views.login_user, name='login'),
    path("logout/", views.logout_user, name="logout"),
]

main/urls.py
# from django.urls import path
# from . import views

# app_name = "main"
# urlpatterns = [
#     path('',views.home, name="home"),
#     path('details/<int:id>/',views.detail, name="detail"),
# ]


from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.home, name="home"),  # URL pattern for the home page
    path('details/<int:id>/', views.detail, name="detail"),  # URL pattern for details page with ID parameter
    path('addmovies/', views.add_movies, name="add_movies"),
    path('editmovies/<int:id>/', views.edit_movies, name="edit_movies"),
    path('deletemovies/<int:id>/', views.delete_movies, name="delete_movie"),
    path('addreview/<int:id>/',views.add_review,name="add_review"),
    path("editreview/<int:movie_id>/<int:review_id>/",views.edit_review, name="edit_review"),
    path("deletereview/<int:movie_id>/<int:review_id>/",views.delete_review, name="delete_review")
]

moviereview/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.
class Movie(models.Model):
    # field for the movie table
    name=models.CharField(max_length=300)
    director=models.CharField(max_length=300)
    cast=models.CharField(max_length=500)
    description=models.CharField(max_length=5000)
    release_date=models.DateField()
    averaageRating=models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

# class Review(models.Model):
#     movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     comment = models.TextField(max_length=1000)
#     rating = models.FloatField(default=0)

#     def __str__(self):
#         return self.user.username


class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username  # Corrected attribute name to 'username'

main/forms.py
from django import forms
from .models import *

#movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast','description', 'release_date', 'image')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

from .models import Movie, Review
from .forms import ReviewForm
from django.db.models import Avg

# Create your views here.
def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()

    
    context = {
        "movies": allMovies,
    }

    return render(request,'main/index.html', context)


#detail page

def detail(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average,2)
    context = {
        "movie": movie,
        "reviews": reviews,
        "average":average
    }
    return render(request, 'main/details.html', context)
    
# add movies to db
# def add_movies(request):
#     if request.method == "POST":
#         form = MovieForm(request.POST or None)

#         # check if the form is valid
#         if form.is_valid():
#             data = form.save(commit=False)
#             data.save()
#             return redirect("main:home")
#         else:
#             form = MovieForm()
#         return render(request, 'main/addmovies.html',{"form": form})

def add_movies(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST)  # Create form instance with POST data
                if form.is_valid():  # Check if the form is valid
                    form.save()  # Save the form data to the database
                    return redirect("main:home")  # Redirect to the home page
            else:
                form = MovieForm()  # Create a new empty form for GET requests

            # Render the addmovies.html template with the form
            return render(request, 'main/addmovies.html', {"form": form,"controller": "Add Movies"})

        # if not admin
        else:
            return redirect("main:home")
            
    return redirect("accounts:login")

# edit movie

def edit_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # movies linked with id
            movie = Movie.objects.get(id=id)
            
            # form check
            if request.method == "POST":
                form = MovieForm(request.POST or None, instance = movie)
                #check form validty
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:detail", id)
            else:
                form = MovieForm(instance=movie)
            return render(request, 'main/addmovies.html',{"form":form, "controller":"Edit Movies"})
     # if not admin
        else:
            return redirect("main:home")
            
    return redirect("accounts:login")


# delete movie

def delete_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            movie = Movie.objects.get(id=id)

            movie.delete()
            return redirect ("main:home")

        else:
            return redirect("main:home")
            
    return redirect("accounts:login")

# def add_review(request,id):
#     if request.user.is_authenticated:
#         movie = Movie.objects.get(id=id)
#         if request.method == "POST":
#             form = ReviewForm(request.POST or None)
#             if form.is_valid():
#                 data = form.save(commit=False)
#                 data.rating= request.POST["comment"]
#                 data.user = request.user
#                 data.movie = movie
#                 data.save()
#                 return redirect("main:detail",id)
#         else:
#             form = ReviewForm()
#         return render(request,'main/details.html',{"form":form})
#     else:
#         return redirect("accounts:login")



def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form, "movie": movie})
    else:
        return redirect("accounts:login")


def edit_review(request, movie_id,  review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id = movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        #check if the review was done by loged in user
        if request.user == review.user:
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                        error = "Out of range. select Rating from 0 to 10 "
                        return render(request, "main/editreview.html", {"error":error, "form":form})
                    else:
                        data.save()
                        return redirect("main:detail", movie_id)
            else:
                form = ReviewForm(instance=review)
            return render(request,"main/editreview.html",{"form":form})
        else:
            return redirect("main:detail",movie_id)
    else:
        return redirect("accounts:login")

# delete review 
def delete_review(request, movie_id,  review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id = movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        #check if the review was done by loged in user
        if request.user == review.user:
            #grant permissioin
            review.delete()

        return redirect("main:detail",movie_id)
    else:
        return redirect("accounts:login")

main/templates/main/addmovies.html
{% extends 'main/base.html' %}



{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>Movie Review</title>

    

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'main:home' %}">Rate</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add_movies' %}">Add Movies</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            {% endif %}

          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="background-color: #5fa855; color: #FFFFFF;">Search</button>
          </form>
        </div>
      </nav>
    {% block content %}


    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
        <div class="card">
            <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
                </div>
                <div class="col-md-8">
                    <h3 class="text-center">
                        {{ movie.name }}
                    </h3>
                    <p>{{ movie.description }}</p>
                    <h5>Director: {{ movie.director }}</h5>
                    <h5>Cast: {{ movie.cast }}</h5>
                    <h5>Rating: {{ average }}/10</h5>

                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">Edit Movie</a>
                            <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?');">Delete Movie</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Reviews</h3>
            <form action="{% url 'main:add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">Rating</label>
                <input type="range" id="rangeInput" name="rating" min="0" max="10" value="0" step="0.5" oninput="amount.value=rangeInput.value">

                <output name="amount" id="amount" for="rangeInput">0</output>

                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
            <div class="card" style="background-color: #f5eeee;">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="text-left">{{ review.user.username }}</h5>
                            <h5>{{ review.rating }}</h5>
                            {% if request.user == review.user %}
                            <a href="{% url 'main:edit_review' movie.id review.id %}">Edit</a>
                            <a href="{% url 'main:delete_review' movie.id review.id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                            {% endif %}

                        </div>
                        <div class="col-md-9">
                            <p>{{ review.comment }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html' %}



{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                                <h3 class="text-center">{{ movie.name }}</h3>
                                <i>{{ movie.release_date}}</i>
                                <a href="{% url 'main:detail' movie.id %}">Read More</a>
                            </div>
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}